feat: implemented search settings in general settings
Zextras/carbonio-shell-ui pull request #2
Opened 2022-01-13 06:52 UTC by dhavaldodiya

- implemented the search settings options in general settings

2022-01-13 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zextras/carbonio-shell-ui?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zextras/carbonio-shell-ui?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zextras/carbonio-shell-ui?pullRequest=2) it.</sub>

2022-01-14 10:43 UTC, giuliano176 requested changes

2022-01-14 10:43 UTC, giuliano176 commented on translations/en.json
> +                "search_settings_label": "Search"
the key search.app has already the same value, please use that key instead of creating a new one

2022-01-14 10:43 UTC, giuliano176 commented on src/settings/search-settings-view.tsx
> +			label={t('settings.search_settings.headings.search_settings_label', 'Search')}
please use the key search.app

2022-01-18 11:42 UTC, zovomat commented
@dhavaldodiya please sign the CLA

2022-01-18 18:08 UTC, zovomat submitted a review, later dismissed

2022-01-20 01:35 UTC, giuliano176 approved these changes, later dismissed

2022-01-20 08:13 UTC, zovomat approved these changes

2022-01-20 08:16 UTC, giuliano176 approved these changes

2022-01-20 08:18 UTC, geeky-abhishek approved these changes

2022-01-20 08:18 UTC, merged