feat: changed behaviour of new button for search and settings modules
Zextras/carbonio-shell-ui pull request #27
Opened 2022-02-28 14:50 UTC by giuliano176

2022-03-04 06:59 UTC, geeky-abhishek submitted a review, later dismissed

2022-03-04 08:09 UTC, nubsthead approved these changes, later dismissed

2022-03-04 08:13 UTC, dhavaldodiya submitted a review, later dismissed

2022-03-04 09:08 UTC, zovomat requested changes

2022-03-04 09:08 UTC, zovomat commented on src/shell/creation-button.tsx
> +	return primaryAction ? (
```suggestion
	return !primaryAction ? (
```

2022-03-04 09:09 UTC, zovomat approved these changes

2022-03-07 07:43 UTC, geeky-abhishek approved these changes

2022-03-07 07:57 UTC, dhavaldodiya approved these changes

2022-03-07 08:19 UTC, nubsthead approved these changes

2022-03-07 09:05 UTC, merged